In [2]:
import pandas as pd

df = pd.read_csv("archive/bollywood.csv", encoding="latin1")
actors = pd.read_csv("archive/bollywood-actors.csv", encoding="latin1")
actress = pd.read_csv("archive/bollywood-actress.csv", encoding="latin1")

In [19]:
#Add a "Role" column to actors ("Actor") and actress ("Actress"). 
# Concat both into df_talent. How many people total? Check df_talent.head() — 
# what happened to "Debut aslead role" for actor rows?
actors["Role"] = "actor"
actress["Role"] = "actress"
df_talent = pd.concat([actors,actress])
df_talent["Role"].value_counts()
df_talent.head()

                  Name  Height(in cm)   Role Debut aslead role  ÿÿ
0  Aaditya Shrivastava            178  actor               NaN NaN
1           Aamir Khan            163  actor               NaN NaN
2           Abhay Deol            180  actor               NaN NaN
3    Abhishek Bachchan            186  actor               NaN NaN
4      Aditya Pancholi            185  actor               NaN NaN

In [ ]:
#From df_talent, filter people taller than 180cm. Sort tallest first.
df_talent.query('`Height(in cm)` > 180').sort_values("Height(in cm)", ascending=False)

                     Name  Height(in cm)   Role Debut aslead role  ÿÿ
5       Aditya Roy Kapoor            188  actor               NaN NaN
43             Imran Khan            188  actor               NaN NaN
25             Dara Singh            188  actor               NaN NaN
63           Kunal Kapoor            188  actor               NaN NaN
60          Kartik Aaryan            188  actor               NaN NaN
83   Priyanshu Chatterjee            188  actor               NaN NaN
81            Prem Chopra            188  actor               NaN NaN
115      Shatrughan Sinha            188  actor               NaN NaN
93         Rana Daggubati            186  actor               NaN NaN
3       Abhishek Bachchan            186  actor               NaN NaN
12       Amitabh Bachchan            185  actor               NaN NaN
17           Arjun Rampal            185  actor               NaN NaN
4         Aditya Pancholi            185  actor               NaN NaN
112         Shammi Kapoor            185  actor               NaN NaN
38          Harman Baweja            185  actor               NaN NaN
120             Sonu Sood            185  actor               NaN NaN
123            Sunil Dutt            183  actor               NaN NaN
34             Feroz Khan            183  actor               NaN NaN
50              Jeetendra            183  actor               NaN NaN
47          Jackie Shroff            183  actor               NaN NaN
45            Irrfan Khan            183  actor               NaN NaN
133         Vicky Kaushal            183  actor               NaN NaN
78           Paresh Rawal            183  actor               NaN NaN
69     Mithun Chakraborty            183  actor               NaN NaN
79                Prabhas            183  actor               NaN NaN
104           Sanjay Dutt            183  actor               NaN NaN
52           John Abraham            182  actor               NaN NaN
65            Manish Paul            182  actor               NaN NaN
94          Ranbir Kapoor            181  actor               NaN NaN

In [28]:
#Print df["Release Month"].unique(). Spot the typo.
#  Fix it with .replace(), confirm with value_counts().
import numpy as np
df["Release Month"].unique()
df["Release Month"] = df["Release Month"].replace("JUl","JUL")
df["Release Month"] = df["Release Month"].replace(np.nan, "Unknown")
df["Release Month"].value_counts()

Release Month
Unknown    8361
OCT         140
MAR         124
SEP         124
MAY         118
AUG         117
APR         110
NOV         108
FEB         107
JAN         104
JUL         104
JUN          86
DEC          78
MM            1
Name: count, dtype: int64

In [31]:
#df["Genre"].nunique() — print it. 
# Then compare: how many rows have Genre exactly equal to 
# "action" vs how many contain "action" anywhere (case-insensitive)?
df["Genre"].nunique()

623

In [39]:
df[df["Genre"]=="action"]["Genre"].value_counts()

Genre
action    747
Name: count, dtype: int64

In [44]:
df["Genre"].str.contains("action",case=False).value_counts()

Genre
False    8206
True     1476
Name: count, dtype: int64