In [5]:
import pandas as pd
bollywood = pd.read_csv('archive/bollywood.csv',encoding='latin-1')

In [6]:
bollywood.head()

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane,unknown,mythology,NaN,NaN,NaN
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar,"koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...",social,NaN,NaN,NaN

In [8]:
print(bollywood.shape)
bollywood.info

(9682, 8)

<bound method DataFrame.info of       Year                                              Title  \
0     1920                     Balika Badhu a.k.a. Baby Bride
1     1920                   Daksha Yagna a.k.a. Sati Parvati
2     1920          Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda
3     1920          Kansa Vadha a.k.a. End Of The Tyrant King
4     1920  Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...
...    ...                                                ...
9677  2019                                            Panipat
9678  2019                                Pati, Patni Aur Woh
9679  2019                                         Mardaani 2
9680  2019                                          Dabangg 3
9681  2019                                          Good News

                             Director  \
0     P. T. Shaida (Tulsidutt Shaida)
1                  Vishnupant Divekar
2                          G. V. Sane
3                          G. V. Sane
4                      S. N. Patankar
...                               ...
9677               Ashutosh Gowariker
9678                    Mudassar Aziz
9679                     Gopi Puthran
9680                      Prabhu Deva
9681                        Raj Mehta

                                                   Cast           Genre  \
0         shaida,pandit,ali,miss,tarak,bagcha,tulsidutt          social
1                                  prabha,khalil,vaidya       mythology
2                                               unknown       mythology
3                                               unknown       mythology
4     koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...          social
...                                                 ...             ...
9677       Sanjay DuttArjun KapoorKriti SanonKabir Bedi   Action/battle
9678           Kartik AaryanBhumi PednekarAnanya Panday          Comedy
9679  Rani MukherjeeVikram Singh ChauhanShruti Bapna...  Crime Thriller
9680  Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...          Action
9681  Akshay KumarKareena KapoorDiljit DosanjhKiara ...          Comedy

     Release Month  Release Date  Highest Grosser By Year(in crores)
0              NaN           NaN                                 NaN
1              NaN           NaN                                 NaN
2              NaN           NaN                                 NaN
3              NaN           NaN                                 NaN
4              NaN           NaN                                 NaN
...            ...           ...                                 ...
9677           DEC           6.0                                 NaN
9678           DEC           6.0                                 NaN
9679           DEC          13.0                                 NaN
9680           DEC          20.0                                 NaN
9681           DEC          27.0                                 NaN

[9682 rows x 8 columns]>

In [11]:
bollywood.tail(5)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN

In [12]:
bollywood.sample(3)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
2510,1947,Pahela Pyaar,A. P. Kapoor,"n,sunalini,amir,sulochana,david,chatterjee,k,v...",social,NaN,NaN,NaN
4819,1972,Jeet,Adurthi Subba Rao,"kapoor,randhir,babita",romance,NaN,NaN,NaN
8056,2005,Dosti: Friends Forever,Unknown,"kapoor,bobby,juhi,kumar,chawla,deol,akshay,dut...","drama,romance",NaN,NaN,NaN

In [13]:
bollywood.loc[10:20,["Title","Director","Genre"]]

,Title,Director,Genre
10,Narsinh Mehta,"Suchet Singh, Shukle",devotional
11,Ram Janma,G. V. Sane,mythology
12,Rama Or Maya,"Suchet Singh, Shukle",mythology
13,Sairandhri,Baburao Painter,mythology
14,Shakuntala,Suchet Singh,mythology
15,Shakuntala,Shree Nath Patankar,"mythology,drama"
16,Shri Krishna Leela,G. V. Sane,mythology
17,Shri Rama Janma,G. V. Sane,mythology
18,Sita Swayamwar a.k.a. Sita's Marriage,Shree Nath Patankar,mythology
19,The Enchanted Pills a.k.a. Vichitra Gutika,S. N. Patankar,social
20,Vikram Urvashi,Kanjibhai Rathod,mythology

In [14]:
bollywood.iloc[0:5,0:3]

,Year,Title,Director
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida)
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar

In [17]:
bollywood.sort_values(["Year"],ascending=False)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9657,2019,Pal Pal Dil Ke Paas,Sunny Deol,Karan DeolSahher Bambba,Drama/Romance,SEP,20.0,NaN
9650,2019,Batla House,Nikhil Advani,John AbrahamMrunal Thakur,Action,AUG,15.0,NaN
9665,2019,Laal Kaptaan,Navdeep Singh,Saif Ali Khan,Action,OCT,18.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN
9664,2019,Ghost,Vikram Bhatt,Sanaya Irani,Horror Thriller,OCT,18.0,NaN
...,...,...,...,...,...,...,...,...
11,1920,Ram Janma,G. V. Sane,unknown,mythology,NaN,NaN,NaN
10,1920,Narsinh Mehta,"Suchet Singh, Shukle","kanjibhai,rathod",devotional,NaN,NaN,NaN
9,1920,Narasinha Avtar,Shree Nath Patankar,unknown,mythology,NaN,NaN,NaN
15,1920,Shakuntala,Shree Nath Patankar,unknown,"mythology,drama",NaN,NaN,NaN
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN

In [18]:
bollywood.sort_values(["Release Month","Year"],ascending=False)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9653,2019,Chhichhore,Nitesh Tiwari,Sushant Singh RajputShraddha KapoorVarun Sharm...,Comedy-Drama,SEP,6.0,NaN
9654,2019,Dream Girl,Raaj Shaandilyaa,Ayushmann KhurranaNushrat Bharucha,Comedy,SEP,13.0,NaN
9655,2019,Section 375,Ajay Bahl,Akshaye KhannaRicha ChadhaRahul BhatMeera Chopra,crime thriller,SEP,13.0,NaN
9656,2019,The Zoya Factor,Abhishek Sharma,Sonam KapoorDulquer SalmaanSanjay Kapoor,Drama,SEP,20.0,NaN
9657,2019,Pal Pal Dil Ke Paas,Sunny Deol,Karan DeolSahher Bambba,Drama/Romance,SEP,20.0,NaN
...,...,...,...,...,...,...,...,...
16,1920,Shri Krishna Leela,G. V. Sane,unknown,mythology,NaN,NaN,NaN
17,1920,Shri Rama Janma,G. V. Sane,unknown,mythology,NaN,NaN,NaN
18,1920,Sita Swayamwar a.k.a. Sita's Marriage,Shree Nath Patankar,limaye,mythology,NaN,NaN,NaN
19,1920,The Enchanted Pills a.k.a. Vichitra Gutika,S. N. Patankar,"damuanna,dighe,marathe,joshi,gokhale,trymbakra...",social,NaN,NaN,NaN
20,1920,Vikram Urvashi,Kanjibhai Rathod,"n,lina,r,vaidya,valentine",mythology,NaN,NaN,NaN

In [19]:
bollywood.query('Year>2000')

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
7590,2001,Abhay,Suresh Krishna,"tandon,koirala,manisha,hassan,raveena,kamal",thriller,NaN,NaN,NaN
7591,2001,Aamdani Atthani Kharcha Rupaiyaa,K. Raghavendra Rao,"tabu,juhi,lever,chawla,koppikar,isha,johnny,go...","family,drama",NaN,NaN,NaN
7592,2001,Aashiq,Indra Kumar,"kapoor,bobby,karisma,deol","action,comedy",NaN,NaN,NaN
7593,2001,Afsana Dilwalon Ka,J. Om Prakash,"kaul,ashish,rahul,juni,roy",romance,NaN,NaN,NaN
7594,2001,Ajnabee,Abbas Mustan,"kapoor,bobby,bipasha,kumar,deol,akshay,basu,ka...","crime,suspense,thriller",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN

In [37]:
bollywood.query('Genre=="action" and Year>2010')

,Year,Title,Director,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
8721,2011,Singham,Rohit Shetty,action,JUL,15.0,NaN,Contemporary
8735,2011,Shabri,Lalit Marathe,action,AUG,26.0,NaN,Contemporary
8800,2012,Tezz,Priyadarshan,action,APR,27.0,NaN,Contemporary
8879,2013,Mumbai Mirror,Ankush Bhatt,action,JAN,18.0,NaN,Contemporary
8885,2013,Vishwaroop,Kamal Haasan,action,FEB,1.0,NaN,Contemporary
8893,2013,Zilla Ghaziabad,Anand Kumar,action,FEB,22.0,NaN,Contemporary
8901,2013,Rangrezz,Priyadarshan,action,MAR,20.0,NaN,Contemporary
8925,2013,Enemmy,Ashu Trikha,action,JUN,21.0,NaN,Contemporary
8929,2013,Policegiri,K. S. Ravikumar,action,JUL,5.0,NaN,Contemporary
8978,2013,Singh Saab The Great,Anil Sharma,action,NOV,22.0,NaN,Contemporary
8983,2013,Dhoom 3,Vijay Krishna Acharya,action,DEC,20.0,589.2,Contemporary
8999,2014,Gunday,Ali Abbas Zafar,action,FEB,14.0,NaN,Contemporary
9020,2014,Dishkiyaoon,Sanamjit Talwar,action,MAR,28.0,NaN,Contemporary
9037,2014,Angry Young Man,Ramesh Rout,action,MAY,2.0,NaN,Contemporary
9041,2014,Koyelaanchal,Ashu Trikha,action,MAY,9.0,NaN,Contemporary
9049,2014,Kochadaiiyaan,Soundarya Rajnikanth,action,MAY,23.0,NaN,Contemporary
9068,2014,Singham Returns,Rohit Shetty,action,AUG,15.0,NaN,Contemporary
9085,2014,Bang Bang!,Siddharth Anand,action,OCT,2.0,NaN,Contemporary
9186,2015,Baahubali,S. S. Rajamouli,action,JUL,10.0,NaN,Contemporary
9228,2015,Ranbanka,Aryeman Ramsay,action,NOV,6.0,NaN,Contemporary
9266,2016,Rocky Handsome,Nishikant Kamat,action,MAR,25.0,NaN,Contemporary
9272,2016,Laal Rang,Syed Ahmad Afzal,action,APR,22.0,NaN,Contemporary
9274,2016,Baaghi,Sabbir Khan,action,APR,29.0,NaN,Contemporary
9281,2016,Khel Toh Ab Shuru Hoga,Kunal V Singh,action,MAY,13.0,NaN,Contemporary
9286,2016,Veerappan,Ram Gopal Varma,action,MAY,27.0,NaN,Contemporary
9308,2016,Kabali,Pa. Ranjith,action,JUL,29.0,NaN,Contemporary
9309,2016,Dishoom,Rohit Dhawan,action,JUL,29.0,NaN,Contemporary
9317,2016,Waarrior Savitri,Param Gill,action,AUG,25.0,NaN,Contemporary
9351,2016,Force 2,Abhinay Deo,action,NOV,18.0,NaN,Contemporary
9367,2017,The Ghazi Attack,Sankalp Reddy,action,FEB,17.0,NaN,Contemporary
9373,2017,Commando 2,Deven Bhojani,action,MAR,3.0,NaN,Contemporary
9433,2017,Babumoshai Bandookbaaz,Kushan Nandy,action,AUG,25.0,NaN,Contemporary
9452,2017,Mein Terrorist Nahi Hoon,Arjin Uppal,action,OCT,6.0,NaN,Contemporary

In [26]:
bollywood.loc[bollywood["Director"].str.contains("chopra",case=False)]

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
2764,1949,Karwat,"Prakash, B.R. Chopra (uncredited)","vasantrao,anwaribai,ratanpriya,deepak,baburao,...",action,NaN,NaN,NaN
2917,1951,Afsana,B. R. Chopra,"veena,kumar,pran,jeevan,ashok","crime,romance,thriller",NaN,NaN,NaN
3178,1953,Shole,B. R. Chopra,"musharaf,master,rai,naaz,bina,kumar,krishna,ro...","social,family,drama",NaN,NaN,NaN
3207,1954,Chandni Chowk,B. R. Chopra,"meena,kumari,smriti,achala,sachdev,katju,yasho...",unknown,NaN,NaN,NaN
3447,1956,Ek Hi Rasta,B. R. Chopra,"meena,kumari,kumkum,daisy,yashodra,kumar,brahm...","social,drama",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9015,2014,W,Tarun Madan Chopra,"sonal,danish,giani,pandor,leslie,meer,abhey,al...",thriller,MAR,14.0,NaN
9356,2016,Befikre,Aditya Chopra,"kapoor,singh,ranveer,vaani",romance,DEC,9.0,NaN
9458,2017,Ittefaq,Abhay Chopra,"sinha,sonakshi,sidharth,khanna,malhotra,akshaye",thriller,NOV,3.0,NaN
9607,2019,Ek Ladki Ko Dekha Toh Aisa Laga,Shelly Chopra Dhar,Anil KapoorSonam KapoorJuhi ChawlaRajkummar Rao,Romance,FEB,1.0,NaN
9672,2019,Shikara - A Love Letter from Kashmir,Vidhu Vinod Chopra,TBA,Historical/Romance,NOV,8.0,NaN

In [28]:
def get_era(Year):
    if Year<1980:
        return "Classic"
    elif Year<2010:
        return "Modern"
    else:
        return "Contemporary"
bollywood["Era"] = bollywood["Year"].apply(get_era)
bollywood[["Year","Title","Era"]].head()

   Year                                              Title      Era
0  1920                     Balika Badhu a.k.a. Baby Bride  Classic
1  1920                   Daksha Yagna a.k.a. Sati Parvati  Classic
2  1920          Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda  Classic
3  1920          Kansa Vadha a.k.a. End Of The Tyrant King  Classic
4  1920  Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...  Classic

In [35]:
#bollywood.drop(columns="Cast",inplace=True)
bollywood.rename(columns={"Release Month":"month"},inplace=True)

In [38]:
#Find all drama movies released in December after 1990, sorted by Year newest first. 
# Show only Title, Year, Director.
bollywood[(bollywood["month"] == "DEC") & (bollywood["Year"] > 1990) & (bollywood["Genre"] == "drama")][["Title", "Year", "Director"]].sort_values("Year", ascending=False)

                          Title  Year              Director
9234                    Kajarya  2015      Madhureeta Anand
9115               Take It Easy  2014       Sunil Prem Vyas
9112  Bhopal: A Prayer for Rain  2014            Ravi Kumar
9113        Mumbai Delhi Mumbai  2014        Satish Rajwade
9118          LUV...Phir Kabhie  2014            Ajay Yadav
8982              What the Fish  2013         Gurmmet Singh
8764          The Dirty Picture  2011         Milan Luthria
8662              Isi Life Mein  2010        Vidhi Kasliwal
8660                      Mirch  2010          Vinay Shukla
8665       Ada... A Way of Life  2010          Tanvir Ahmad
8537       Raat Gayi Baat Gayi?  2009        Saurabh Shukla
8437           Meerabai Not Out  2008  Chandrakant Kulkarni